version: '3'
services:
  nitropage:
    image: ${NP_IMAGE}
    env_file: .env
    environment:
      - DATABASE_URL=file:/srv/db/dev.db
      - NP_DEMO=1
    build:
      context: .
      args:
        - VERSION=${NP_VERSION}
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./srv:/srv
